'use strict';

export const FETCH_ARTICLE_LIST = 'FETCH_ARTICLE_LIST';
export const RECEIVE_HOT_LIST = 'RECEIVE_HOT_LIST';
export const RECEIVE_IT_LIST = 'RECEIVE_IT_LIST';
export const RECEIVE_JOKE_LIST = 'RECEIVE_JOKE_LIST';