'use strict';

export const FETCH_ARTICLE_LIST = 'FETCH_ARTICLE_LIST';
export const RECEIVE_ARTICLE_LIST = 'RECEIVE_ARTICLE_LIST';
export const FETCH_TYPE_LIST = 'FETCH_TYPE_LIST';
export const RECEIVE_TYPE_LIST = 'RECEIVE_TYPE_LIST';